services:
  postgres:
    image: postgres:latest
    container_name: travel-wishlist-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel-wishlist-network

volumes:
  postgres_data:

networks:
  travel-wishlist-network:
    driver: bridge