CREATE TABLE consumer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_consumer PRIMARY KEY (id)
);

CREATE TABLE destination
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255),
    consumer_id BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_destination PRIMARY KEY (id)
);

CREATE TABLE message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(255)                            NOT NULL,
    sender_id  BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE consumer
    ADD CONSTRAINT uc_consumer_username UNIQUE (username);

ALTER TABLE destination
    ADD CONSTRAINT FK_DESTINATION_ON_CONSUMER FOREIGN KEY (consumer_id) REFERENCES consumer (id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_SENDER FOREIGN KEY (sender_id) REFERENCES consumer (id);